name: clerk_test
description: "Providing test infrastructure for clerk_auth and clerk_flutter"
version: 0.0.13-beta
publish_to: none
homepage:

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_dotenv: ^1.0.1
  clerk_auth:
    path: ../clerk_auth
  http: ^1.1.0
  test: ^1.25.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
